# Generated by Django 2.2 on 2020-07-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='budget',
            new_name='budget_max',
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_min',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
