# Generated by Django 2.2 on 2020-07-19 21:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_quiz_brief'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lead',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
