# Generated by Django 2.2 on 2020-07-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20200719_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='images',
            new_name='uploads',
        ),
    ]
