# Generated by Django 2.2 on 2020-07-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('leads', '0009_auto_20200721_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='persona_type',
        ),
        migrations.AddField(
            model_name='lead',
            name='persona_type',
            field=models.ManyToManyField(related_name='has_leads', to='quiz.Persona'),
        ),
    ]
