# Generated by Django 2.2 on 2020-07-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20200721_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='persona_type',
            field=models.ManyToManyField(blank=True, related_name='has_leads', to='quiz.Persona'),
        ),
    ]
