# Generated by Django 2.2 on 2020-07-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20200721_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='persona_type',
            new_name='has_persona',
        ),
    ]
