# Generated by Django 2.2 on 2020-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200816_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_type',
            field=models.CharField(choices=[('LW', 'Living Well'), ('HE', 'Hip Enthusiast'), ('CO', 'Collector'), ('NA', 'Unknown')], default='NA', max_length=2),
        ),
    ]
