# Generated by Django 2.2 on 2020-08-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200827_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_type',
            field=models.CharField(choices=[('LIVING_WELL', 'Living Well'), ('HIP_ENTHUSIAST', 'Hip Enthusiast'), ('COLLECTOR', 'Collector'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=45),
        ),
    ]
