# Generated by Django 2.2 on 2020-08-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200828_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_type',
            field=models.CharField(max_length=45),
        ),
    ]
